version: "3.8"

services:
  config-server:
    image: mongo:8.0
    container_name: config-server
    command: ["mongod", "--configsvr", "--replSet", "config-repl-set", "--port", "27017", "--bind_ip_all"]
    ports:
      - "27017:27017"
    networks:
      - mongo-shard-net

  shard1-1:
    image: mongo:8.0
    container_name: shard1-1
    command: ["mongod", "--shardsvr", "--replSet", "shard1-repl-set", "--port", "27018", "--bind_ip_all"]
    ports:
      - "27018:27018"
    networks:
      - mongo-shard-net

  shard1-2:
    image: mongo:8.0
    container_name: shard1-2
    command: ["mongod", "--shardsvr", "--replSet", "shard1-repl-set", "--port", "27019", "--bind_ip_all"]
    ports:
      - "27019:27019"
    networks:
      - mongo-shard-net

  shard1-3:
    image: mongo:8.0
    container_name: shard1-3
    command: ["mongod", "--shardsvr", "--replSet", "shard1-repl-set", "--port", "27020", "--bind_ip_all"]
    ports:
      - "27020:27020"
    networks:
      - mongo-shard-net

  shard2:
    image: mongo:8.0
    container_name: shard2
    command: ["mongod", "--shardsvr", "--replSet", "shard2-repl-set", "--port", "27021", "--bind_ip_all"]
    ports:
      - "27021:27021"
    networks:
      - mongo-shard-net

  shard3:
    image: mongo:8.0
    container_name: shard3
    command: ["mongod", "--shardsvr", "--replSet", "shard3-repl-set", "--port", "27022", "--bind_ip_all"]
    ports:
      - "27022:27022"
    networks:
      - mongo-shard-net

  shard4:
    image: mongo:8.0
    container_name: shard4
    command: ["mongod", "--shardsvr", "--replSet", "shard4-repl-set", "--port", "27023", "--bind_ip_all"]
    ports:
      - "27023:27023"
    networks:
      - mongo-shard-net

  mongos:
    image: mongo:8.0
    container_name: mongos
    command: ["mongos", "--configdb", "config-repl-set/config-server:27017", "--port", "27024", "--bind_ip_all"]
    ports:
      - "27024:27024"
    depends_on:
      - config-server
    networks:
      - mongo-shard-net

networks:
  mongo-shard-net:
    name: mongo-shard-net
    driver: bridge
